spring:
  datasource:
    #    //ip 
    url: jdbc:mysql://centos006:1001/xcplus_orders?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
pay:
  qrcodeurl: localhost:1006/orders/requestpay?payNo=%s
  alipay:
    APPID: 
    PRIVATE_KEY: 
    ALIPAY_PUBLIC_KEY: 
