# keytool -genkey -alias alias -keyalg RSA -keysize 2048 -keystore jwt.jks -validity 365 -keypass keypass -storepass keypass

### AUTHORIZATION_CODE 获取授code  需要response_type+client_id+scope 使用网页登录测试
#GET {{auth_host}}/auth/oauth2/authorize?response_type=code&client_id=xcWebApp&scope=all

### AUTHORIZATION_CODE 获取token
POST {{auth_host}}/auth/oauth2/token?grant_type=authorization_code&client_id=xcWebApp&client_secret=xcWebApp&code=0XohfYnu6NCIqM5o3elWq_ZRttuka3oqdFJyS946BQlldqOSNqXiyNuLmyJWTMNs3W9fRxjSOA7rC0nDAoiZEzkgy3Ad_nRK8JnMyCwW5LPHXMZGL1lxh2l7FY6uQVTe

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE0NzQyMTUsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTU2MDYxNSwiaWF0IjoxNjgxNDc0MjE1LCJpbmZvIjp7ImNvbXBhbnlJZCI6IjEyMzQ1NiIsInVzZXJwaWMiOiJ6a2MiLCJuYW1lIjoiemtjIiwibmlja25hbWUiOiJ6a2MifX0.ktGBZ3rhMsdE1gaOQsQFEvuewzV0KjqJ0ELoyGHKlSei0cb6k4RzMPAeCDFwvXlqCx_0bi5r5EamA9kVmOGMZCsiHm47bvv_4_bObeFNHWtrXEXf-u58DwGQIzKL85HFrOippX_eXgD0A7Q_m22tao3DfWuTLvkIG5pJlB3amUrThFs9ydVFpwb-RqlCCp8DlatHBNwHz5OpdxTdSf-FIGkwOpPMQs7NEPp7cHHMte8In9uJiXUlonEPtO9StmHA2XHyCLdFViIxj66-CKJ1HO83JGUQMEp8cgep8Eu7Hi4srU5K22APEbXLKDz5RsJ0jY-x38cvRy3ZvCzR1veqfQ",
#  "refresh_token": "Tw_nr73pOwGrAokUIngZLpAk-EPQgkkrT3neoqA-x94URwz1_OsivPSJDqsZKa3WdxRxjDfbaTlH2LemJGErDYxm_bHldrrirwX_9be993CsoaFGksYZSGH-vDML4Bcj",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86399
#}

### Refreshing an Access Token 
POST {{auth_host}}/auth/oauth2/token?grant_type=refresh_token&client_id=xcWebApp&client_secret=xcWebApp&refresh_token=Y2R91WOtZXusEuEvKJP7GDRgLE1ESB0grf7u45JWF0dYXKojwX_Tjm9IJrzvdmeXJrEWnP_-e3Q6cozYjHcNUQYict5ajxMUNXzyyNaw7iGbqRu_-Ul3mOvrP2Cx188u

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE0NjYyNTIsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTU1MjY1MiwiaWF0IjoxNjgxNDY2MjUyfQ.AutXUOIYVKY6-tjfMIFHGPWA-zOf6KcgGLBFNcPDP3MSHEBBHnO6REePNkpqvWcUbiGNfQ4Z1LDJT0guJWDUawng4giWxtBwiDP38duWXXpkc3_UJXPekCp4nrNh6Ny31h8T6Z4ilIOFG-wp3merflsvLw4ThTznSxsXnfRahQ6gYOaiKTXish1a5yIr8u2fR7S07v5iAbS19n7PIA1g7byK6T6aPgOvxZcGqOuUl-489Ft3EM4abE9YpKA3ay4kz6dyiryZ6roP4V-lIGMpBYC_AtI6he6DDEEGQHigToImxWdCYTMXDgcYEafT44-sr0Cg8Wb5sUAHYBV5mjf_8Q",
#  "refresh_token": "LXgOeH1vlzqIqfe8EpJLl0wYbu396MpOd8URqC4b2ps3Txa9hJV8H9gCscbKrd2u6h0rvti0VVHFfosOT3beQhrdpBW4X76CZyLYLM76hftNPEcOQ0ulaUvrrA50uTbB",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86400
#}


### PASSWORD 获取token
POST {{auth_host}}/auth/oauth2/token?grant_type=password&client_id=xcWebApp&client_secret=xcWebApp&username=test&password=123

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE0NzQyNjYsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTU2MDY2NiwiaWF0IjoxNjgxNDc0MjY2LCJpbmZvIjp7ImNvbXBhbnlJZCI6IjEyMzQ1NiIsInVzZXJwaWMiOiJ6a2MiLCJuYW1lIjoiemtjIiwibmlja25hbWUiOiJ6a2MifX0.F-_tvbxqfy2AtQPve9rbYe3H0zRipoXVQwPW_tdhJA_F7I7OYKgZXeY2o9B7-bPyILocvc_TsfGmbdCppCULrRun-lFSTqyGVr2F7mj2J75NwnxhRV4aiFxNTUGhaDquqvfAXw-sK4aX3rPVgSTWCYewG3V9t8aKq4VSqIQ8U7HeP6SQixqsz6Q3fViSB4Mun80VWOeOnxdKAlBTwiUx5-U11haxy_xN988tcHwQMzRlmY5QtQqrw2kPV0u7xQgcZ1JDMMrpDW3VY79k5wKuUcZsVDyPIjKpeOqB5jnHs1VcNrD51rIHGxG4Mm5r2XY1oOa1730uwbIIUu-KBTSOEg",
#  "refresh_token": "0OdiaWw6mnCqOzFljwSarJW0Q6V8yy3vxOa9mtUGmp8N9U5af0BCnwciZsuJJQM1_Oowp89u4TjqHW0N6coRcbjskkw4nCDxfAUlF2TGq0vVknrevIl-VfS-illBwL1M",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86400
#}


### test
GET {{auth_host}}/auth/test/success



### jwk
GET {{auth_host}}/auth/oauth2/jwks
