
### 获取课程列表
POST {{content_host}}/coursebase/list?pageno=1&pagesize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "java",
  "publishStatus": ""
}


### 获取课程分类
GET {{content_host}}/coursecategory/treeNodes?parentId=1

