# keytool -genkey -alias alias -keyalg RSA -keysize 2048 -keystore jwt.jks -validity 365 -keypass keypass -storepass keypass

### AUTHORIZATION_CODE 获取授code  需要response_type+client_id+scope 使用网页登录测试
#GET {{auth_host}}/auth/oauth2/authorize?response_type=code&client_id=xcWebApp&scope=all

### AUTHORIZATION_CODE 获取token
POST {{auth_host}}/auth/oauth2/token?grant_type=authorization_code&client_id=xcWebApp&client_secret=xcWebApp&code=hXTlT6ddu_UaJdJpWdgyTprTedAopf50Qh4puNfhUlvG8VRh-lrkmjdwBTwHwhbssrsGr39HOb_851IQz0Lhwr2QQuyEzt25S5ETWC2y47c7chF39AsPyxVTfR-MOAfX

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE1NjA1NzEsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTY0Njk3MSwiaWF0IjoxNjgxNTYwNTcxLCJ1c2VyaW5mbyI6eyJpZCI6IjUzIiwidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOm51bGwsInNhbHQiOm51bGwsInd4VW5pb25pZCI6bnVsbCwibmlja25hbWUiOiJ6a2MiLCJuYW1lIjoiemtjIiwidXNlcnBpYyI6bnVsbCwiY29tcGFueUlkIjoiMSIsInV0eXBlIjoiMTAxMDAzIiwiYmlydGhkYXkiOm51bGwsInNleCI6IjEiLCJlbWFpbCI6bnVsbCwiY2VsbHBob25lIjpudWxsLCJxcSI6bnVsbCwic3RhdHVzIjoiMSIsImNyZWF0ZVRpbWUiOiJBcHIgMTQsIDIwMjMsIDY6MTE6NTYgUE0iLCJ1cGRhdGVUaW1lIjpudWxsfX0.T3c_J9j6bakeB2k295hfcEQkhC7m0a37HLOH3tjnDP3KP3_dGVvdEpsEfUnM79gIziQ8UJq1FETbwuY_AsFD-f39vIy6W4Q5PL2XsMLxMrmqcvHoeoaa-v4D5wk7Gb8OhSTAaI-Ds0QtvKkAAW-0IqAYYpFAnFu9B4tAwExiuYIWvLbf85dBbqf5kJa1nPrgRdT8dIos9FZBBOOmcBF461V_iUNjzjEA3utztN5ctWuVXbwJYGSAW0N569K5CUYARuIMN_eeVbTCcp0zTCYN4hit5bZQoWHuWl3DuiBUIZhEas9vR1HvmpVcfI9drVpErjRIZgDl4Iljor50atx43Q",
#  "refresh_token": "8QurRaQvc4Taj-_wVsdwQWKhfODqSlrP_LglOe0csvbSkVS8ejzHNH4ENxeVsRORd6dfYbO1MJffSB-jB7ex6pRIYRXpPYOJFi4n1MADojZmh6hhpknY4tIcsKxVLiAb",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86399
#}

### Refreshing an Access Token 
POST {{auth_host}}/auth/oauth2/token?grant_type=refresh_token&client_id=xcWebApp&client_secret=xcWebApp&refresh_token=Y2R91WOtZXusEuEvKJP7GDRgLE1ESB0grf7u45JWF0dYXKojwX_Tjm9IJrzvdmeXJrEWnP_-e3Q6cozYjHcNUQYict5ajxMUNXzyyNaw7iGbqRu_-Ul3mOvrP2Cx188u

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE0NjYyNTIsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTU1MjY1MiwiaWF0IjoxNjgxNDY2MjUyfQ.AutXUOIYVKY6-tjfMIFHGPWA-zOf6KcgGLBFNcPDP3MSHEBBHnO6REePNkpqvWcUbiGNfQ4Z1LDJT0guJWDUawng4giWxtBwiDP38duWXXpkc3_UJXPekCp4nrNh6Ny31h8T6Z4ilIOFG-wp3merflsvLw4ThTznSxsXnfRahQ6gYOaiKTXish1a5yIr8u2fR7S07v5iAbS19n7PIA1g7byK6T6aPgOvxZcGqOuUl-489Ft3EM4abE9YpKA3ay4kz6dyiryZ6roP4V-lIGMpBYC_AtI6he6DDEEGQHigToImxWdCYTMXDgcYEafT44-sr0Cg8Wb5sUAHYBV5mjf_8Q",
#  "refresh_token": "LXgOeH1vlzqIqfe8EpJLl0wYbu396MpOd8URqC4b2ps3Txa9hJV8H9gCscbKrd2u6h0rvti0VVHFfosOT3beQhrdpBW4X76CZyLYLM76hftNPEcOQ0ulaUvrrA50uTbB",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86400
#}


### PASSWORD 获取token
POST {{auth_host}}/auth/oauth2/token?grant_type=password&client_id=xcWebApp&client_secret=xcWebApp&username=test&password=123

#{
#  "access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXVkIjoieGNXZWJBcHAiLCJuYmYiOjE2ODE0NzQyNjYsInNjb3BlIjpbImFsbCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjEwMTkvYXV0aCIsImV4cCI6MTY4MTU2MDY2NiwiaWF0IjoxNjgxNDc0MjY2LCJpbmZvIjp7ImNvbXBhbnlJZCI6IjEyMzQ1NiIsInVzZXJwaWMiOiJ6a2MiLCJuYW1lIjoiemtjIiwibmlja25hbWUiOiJ6a2MifX0.F-_tvbxqfy2AtQPve9rbYe3H0zRipoXVQwPW_tdhJA_F7I7OYKgZXeY2o9B7-bPyILocvc_TsfGmbdCppCULrRun-lFSTqyGVr2F7mj2J75NwnxhRV4aiFxNTUGhaDquqvfAXw-sK4aX3rPVgSTWCYewG3V9t8aKq4VSqIQ8U7HeP6SQixqsz6Q3fViSB4Mun80VWOeOnxdKAlBTwiUx5-U11haxy_xN988tcHwQMzRlmY5QtQqrw2kPV0u7xQgcZ1JDMMrpDW3VY79k5wKuUcZsVDyPIjKpeOqB5jnHs1VcNrD51rIHGxG4Mm5r2XY1oOa1730uwbIIUu-KBTSOEg",
#  "refresh_token": "0OdiaWw6mnCqOzFljwSarJW0Q6V8yy3vxOa9mtUGmp8N9U5af0BCnwciZsuJJQM1_Oowp89u4TjqHW0N6coRcbjskkw4nCDxfAUlF2TGq0vVknrevIl-VfS-illBwL1M",
#  "scope": "all",
#  "token_type": "Bearer",
#  "expires_in": 86400
#}


### test
GET {{auth_host}}/auth/test/success



### jwk
GET {{auth_host}}/auth/oauth2/jwks
