spring:
  datasource:
    #    //ip 
    url: jdbc:mysql://centos006:1001/xcplus_media?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  # -Dserver.port=1012 -Dxxl.job.executor.port=1013
 ##本地配置参数不被覆盖。 xxljob分片测试时需要运行多个执行器 使用本地参数重新指定端口
  cloud:
    config:
      override-none: true 
mybatis-plus:
  mapper-locations:
    - classpath*:dao/*.xml     #修改默认文件后 指定自定义位置
minio:
  endpoint: http://192.168.164.133:1008
  access-key: root
  secret-key: 123456xxx
  bucket: 
    #音频视频
    default: xcplus
    #分片合并上传测试使用
    bigfile: xcplus-bigfile
    #页面静态化
    html: xcplus-html
xxl:
  job:
    ### 调度器与执行器通讯TOKEN
    accessToken: 123456xxx
    admin:
      ### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://centos006:1010/xxl-job-admin
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: videoformatter
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address: 
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 192.168.1.4
      ### (单独的服务端口)执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 1011
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；（win下不指定盘符则在执行器所在盘根目录）
      logpath: /xxl-job-executor/logs
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
videoprocess:
  ffmpegpath: E:\浏览器下载\xcplus\ffmpeg\ffmpeg.exe