server:
  port: 1007
  servlet:
    context-path: /media #项目路径，构成url地址的一部分。
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB 
      max-request-size: 1024MB
swagger:
  title: 在线内容管理系统
  description: 内容管理系统媒资管理接口文档
