spring:
  datasource:
    #    //ip 
    url: jdbc:mysql://centos006:1001/xcplus_system?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations:
    - classpath*:dao/*.xml     #修改默认文件后 指定自定义位置