spring: 
  data:
    redis:
      password: 123456xxx
      timeout: 10000
      database: 0
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 0
      host: centos006
      port: 1021