spring:
  application:
    name: xcplus-content-api
  datasource:
#    //ip 
    url: jdbc:mysql://centos006:1001/xcplus_content?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 1002
logging:
  config: classpath:log4j2-dev.xml
