spring:
  application:
    name: xcplus-content-api
server:
  port: 1001
logging:
  config: classpath:log4j2-dev.xml
#swagger:
#  title: "在线内容管理系统"
#  description: "对课程相关信息进行管理"
#  base-package: com.zkc.xcplus.content

#  version: 1.0.0